//
// April 24, 2026
// Very simple proto file for testing
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: mockup.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Controller query for state and response
type StateQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           string                 `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateQuery) Reset() {
	*x = StateQuery{}
	mi := &file_mockup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateQuery) ProtoMessage() {}

func (x *StateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_mockup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateQuery.ProtoReflect.Descriptor instead.
func (*StateQuery) Descriptor() ([]byte, []int) {
	return file_mockup_proto_rawDescGZIP(), []int{0}
}

func (x *StateQuery) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_mockup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_mockup_proto_rawDescGZIP(), []int{1}
}

func (x *StateResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type HeadCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       string                 `protobuf:"bytes,1,opt,name=Present,proto3" json:"Present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadCount) Reset() {
	*x = HeadCount{}
	mi := &file_mockup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadCount) ProtoMessage() {}

func (x *HeadCount) ProtoReflect() protoreflect.Message {
	mi := &file_mockup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadCount.ProtoReflect.Descriptor instead.
func (*HeadCount) Descriptor() ([]byte, []int) {
	return file_mockup_proto_rawDescGZIP(), []int{2}
}

func (x *HeadCount) GetPresent() string {
	if x != nil {
		return x.Present
	}
	return ""
}

var File_mockup_proto protoreflect.FileDescriptor

const file_mockup_proto_rawDesc = "" +
	"\n" +
	"\fmockup.proto\x12\asandbox\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\n" +
	"StateQuery\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\tR\x03ask\"%\n" +
	"\rStateResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"%\n" +
	"\tHeadCount\x12\x18\n" +
	"\aPresent\x18\x01 \x01(\tR\aPresent2}\n" +
	"\aTraffic\x12:\n" +
	"\tYourState\x12\x13.sandbox.StateQuery\x1a\x16.sandbox.StateResponse\"\x00\x126\n" +
	"\x04Data\x12\x16.google.protobuf.Empty\x1a\x12.sandbox.HeadCount\"\x000\x012\x80\x01\n" +
	"\x06Bridge\x126\n" +
	"\x04Data\x12\x12.sandbox.HeadCount\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12>\n" +
	"\tYourState\x12\x16.sandbox.StateResponse\x1a\x13.sandbox.StateQuery\"\x00(\x010\x01B\x0eZ\fmockup/protob\x06proto3"

var (
	file_mockup_proto_rawDescOnce sync.Once
	file_mockup_proto_rawDescData []byte
)

func file_mockup_proto_rawDescGZIP() []byte {
	file_mockup_proto_rawDescOnce.Do(func() {
		file_mockup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mockup_proto_rawDesc), len(file_mockup_proto_rawDesc)))
	})
	return file_mockup_proto_rawDescData
}

var file_mockup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mockup_proto_goTypes = []any{
	(*StateQuery)(nil),    // 0: sandbox.StateQuery
	(*StateResponse)(nil), // 1: sandbox.StateResponse
	(*HeadCount)(nil),     // 2: sandbox.HeadCount
	(*empty.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_mockup_proto_depIdxs = []int32{
	0, // 0: sandbox.Traffic.YourState:input_type -> sandbox.StateQuery
	3, // 1: sandbox.Traffic.Data:input_type -> google.protobuf.Empty
	2, // 2: sandbox.Bridge.Data:input_type -> sandbox.HeadCount
	1, // 3: sandbox.Bridge.YourState:input_type -> sandbox.StateResponse
	1, // 4: sandbox.Traffic.YourState:output_type -> sandbox.StateResponse
	2, // 5: sandbox.Traffic.Data:output_type -> sandbox.HeadCount
	3, // 6: sandbox.Bridge.Data:output_type -> google.protobuf.Empty
	0, // 7: sandbox.Bridge.YourState:output_type -> sandbox.StateQuery
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mockup_proto_init() }
func file_mockup_proto_init() {
	if File_mockup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mockup_proto_rawDesc), len(file_mockup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mockup_proto_goTypes,
		DependencyIndexes: file_mockup_proto_depIdxs,
		MessageInfos:      file_mockup_proto_msgTypes,
	}.Build()
	File_mockup_proto = out.File
	file_mockup_proto_goTypes = nil
	file_mockup_proto_depIdxs = nil
}
