//
// April 24, 2026
// Very simple proto file for testing
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: mockup.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Traffic_YourState_FullMethodName = "/sandbox.Traffic/YourState"
	Traffic_Data_FullMethodName      = "/sandbox.Traffic/Data"
)

// TrafficClient is the client API for Traffic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficClient interface {
	// Client asking controller for state
	YourState(ctx context.Context, in *StateQuery, opts ...grpc.CallOption) (*StateResponse, error)
	// Server streaming data
	Data(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeadCount], error)
}

type trafficClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficClient(cc grpc.ClientConnInterface) TrafficClient {
	return &trafficClient{cc}
}

func (c *trafficClient) YourState(ctx context.Context, in *StateQuery, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, Traffic_YourState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficClient) Data(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeadCount], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Traffic_ServiceDesc.Streams[0], Traffic_Data_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[empty.Empty, HeadCount]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Traffic_DataClient = grpc.ServerStreamingClient[HeadCount]

// TrafficServer is the server API for Traffic service.
// All implementations must embed UnimplementedTrafficServer
// for forward compatibility.
type TrafficServer interface {
	// Client asking controller for state
	YourState(context.Context, *StateQuery) (*StateResponse, error)
	// Server streaming data
	Data(*empty.Empty, grpc.ServerStreamingServer[HeadCount]) error
	mustEmbedUnimplementedTrafficServer()
}

// UnimplementedTrafficServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficServer struct{}

func (UnimplementedTrafficServer) YourState(context.Context, *StateQuery) (*StateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method YourState not implemented")
}
func (UnimplementedTrafficServer) Data(*empty.Empty, grpc.ServerStreamingServer[HeadCount]) error {
	return status.Errorf(codes.Unimplemented, "method Data not implemented")
}
func (UnimplementedTrafficServer) mustEmbedUnimplementedTrafficServer() {}
func (UnimplementedTrafficServer) testEmbeddedByValue()                 {}

// UnsafeTrafficServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficServer will
// result in compilation errors.
type UnsafeTrafficServer interface {
	mustEmbedUnimplementedTrafficServer()
}

func RegisterTrafficServer(s grpc.ServiceRegistrar, srv TrafficServer) {
	// If the following call pancis, it indicates UnimplementedTrafficServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Traffic_ServiceDesc, srv)
}

func _Traffic_YourState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServer).YourState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Traffic_YourState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServer).YourState(ctx, req.(*StateQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Traffic_Data_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrafficServer).Data(m, &grpc.GenericServerStream[empty.Empty, HeadCount]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Traffic_DataServer = grpc.ServerStreamingServer[HeadCount]

// Traffic_ServiceDesc is the grpc.ServiceDesc for Traffic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Traffic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.Traffic",
	HandlerType: (*TrafficServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "YourState",
			Handler:    _Traffic_YourState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Data",
			Handler:       _Traffic_Data_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mockup.proto",
}

const (
	Bridge_Data_FullMethodName = "/sandbox.Bridge/Data"
	Bridge_Out_FullMethodName  = "/sandbox.Bridge/Out"
	Bridge_In_FullMethodName   = "/sandbox.Bridge/In"
)

// BridgeClient is the client API for Bridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeClient interface {
	Data(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HeadCount, empty.Empty], error)
	// 260522 Bridge streams Queries,  pcol streams Responses back
	Out(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StateResponse, empty.Empty], error)
	In(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateQuery], error)
}

type bridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeClient(cc grpc.ClientConnInterface) BridgeClient {
	return &bridgeClient{cc}
}

func (c *bridgeClient) Data(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HeadCount, empty.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bridge_ServiceDesc.Streams[0], Bridge_Data_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeadCount, empty.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_DataClient = grpc.ClientStreamingClient[HeadCount, empty.Empty]

func (c *bridgeClient) Out(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StateResponse, empty.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bridge_ServiceDesc.Streams[1], Bridge_Out_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateResponse, empty.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_OutClient = grpc.ClientStreamingClient[StateResponse, empty.Empty]

func (c *bridgeClient) In(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateQuery], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bridge_ServiceDesc.Streams[2], Bridge_In_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[empty.Empty, StateQuery]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_InClient = grpc.ServerStreamingClient[StateQuery]

// BridgeServer is the server API for Bridge service.
// All implementations must embed UnimplementedBridgeServer
// for forward compatibility.
type BridgeServer interface {
	Data(grpc.ClientStreamingServer[HeadCount, empty.Empty]) error
	// 260522 Bridge streams Queries,  pcol streams Responses back
	Out(grpc.ClientStreamingServer[StateResponse, empty.Empty]) error
	In(*empty.Empty, grpc.ServerStreamingServer[StateQuery]) error
	mustEmbedUnimplementedBridgeServer()
}

// UnimplementedBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeServer struct{}

func (UnimplementedBridgeServer) Data(grpc.ClientStreamingServer[HeadCount, empty.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Data not implemented")
}
func (UnimplementedBridgeServer) Out(grpc.ClientStreamingServer[StateResponse, empty.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Out not implemented")
}
func (UnimplementedBridgeServer) In(*empty.Empty, grpc.ServerStreamingServer[StateQuery]) error {
	return status.Errorf(codes.Unimplemented, "method In not implemented")
}
func (UnimplementedBridgeServer) mustEmbedUnimplementedBridgeServer() {}
func (UnimplementedBridgeServer) testEmbeddedByValue()                {}

// UnsafeBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServer will
// result in compilation errors.
type UnsafeBridgeServer interface {
	mustEmbedUnimplementedBridgeServer()
}

func RegisterBridgeServer(s grpc.ServiceRegistrar, srv BridgeServer) {
	// If the following call pancis, it indicates UnimplementedBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bridge_ServiceDesc, srv)
}

func _Bridge_Data_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BridgeServer).Data(&grpc.GenericServerStream[HeadCount, empty.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_DataServer = grpc.ClientStreamingServer[HeadCount, empty.Empty]

func _Bridge_Out_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BridgeServer).Out(&grpc.GenericServerStream[StateResponse, empty.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_OutServer = grpc.ClientStreamingServer[StateResponse, empty.Empty]

func _Bridge_In_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BridgeServer).In(m, &grpc.GenericServerStream[empty.Empty, StateQuery]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_InServer = grpc.ServerStreamingServer[StateQuery]

// Bridge_ServiceDesc is the grpc.ServiceDesc for Bridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.Bridge",
	HandlerType: (*BridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Data",
			Handler:       _Bridge_Data_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Out",
			Handler:       _Bridge_Out_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "In",
			Handler:       _Bridge_In_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mockup.proto",
}
