//
// April 24, 2026
// Very simple proto file for testing 
//

syntax = "proto3";
package sandbox;

import  "google/protobuf/empty.proto";


option go_package = "mockup/proto";


// Controller query for state and response
//
message StateQuery {
        string ask = 1;
}
message StateResponse {
        string reply = 2;
}


message HeadCount {
        string Present = 2;
}

message FlowControl {
        int32 onoff = 1;
}

service Traffic {
        // Client asking controller for state
        rpc YourState(StateQuery) returns (StateResponse) {}

        // Server streaming data
        rpc Data(FlowControl) returns (stream  HeadCount) {}
}

service Bridge {
        rpc Data(stream HeadCount) returns (google.protobuf.Empty) {}

        // 260515 This has to be bidir-streaming!
        rpc YourState(stream StateResponse) returns (stream StateQuery) {}
}